FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

COPY src/app/requirements-docker.txt /tmp/
RUN pip install --upgrade pip && pip install --no-cache-dir -r /tmp/requirements-docker.txt

WORKDIR /app
COPY ./src/app .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]